apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: tracker-postgres-db
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: db-workload
    spec:
      containers:
        - name: postgres
          image: docker.io/postgres:9.6.17-alpine
          env:
            - name: POSTGRES_USER
              value: "postgres"
            ...
          ports:
            ...
  parameters:
    - name: dbuser
      ...

